import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "./Component/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en" className="p-6">
      <body className={` ${poppins.variable} antialiased`}>
        <Navbar />
        <hr className="mb-3" />
        <main>{children}</main>
      </body>
    </html>
  );
}
